// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication03.Data;

#nullable disable

namespace WebApplication03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221129144126_Seeded Data to Language Table")]
    partial class SeededDatatoLanguageTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication03.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "e7725861-3177-44ac-bbee-e057723706a4",
                            Name = "Svenska",
                            Register = new DateTime(2022, 11, 29, 15, 41, 26, 220, DateTimeKind.Local).AddTicks(1276)
                        },
                        new
                        {
                            Id = "4c48c2c8-cb47-426a-ae73-6490a5699cfa",
                            Name = "Persiska",
                            Register = new DateTime(2022, 11, 29, 15, 41, 26, 220, DateTimeKind.Local).AddTicks(1315)
                        },
                        new
                        {
                            Id = "a40b55c9-a7ec-4b53-b68f-f5433a67f70d",
                            Name = "Engleska",
                            Register = new DateTime(2022, 11, 29, 15, 41, 26, 220, DateTimeKind.Local).AddTicks(1320)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
