// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication03.Data;

#nullable disable

namespace WebApplication03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221129145453_seeded Data To Country table")]
    partial class seededDataToCountrytable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.Property<string>("LanguagesId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PeopleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LanguagesId", "PeopleId");

                    b.HasIndex("PeopleId");

                    b.ToTable("LanguagePerson");
                });

            modelBuilder.Entity("WebApplication03.Models.City", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = "bc8c6418-8b50-4bac-a230-2c238ca9b10f",
                            Name = "GBG",
                            PostNumber = "415 52",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9218)
                        },
                        new
                        {
                            Id = "08190b49-2610-416e-9209-14bffdc4cb73",
                            Name = "Järpen",
                            PostNumber = "415 55",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9223)
                        },
                        new
                        {
                            Id = "b9c2017b-ac5d-466c-8bd5-ebb4f5b6397d",
                            Name = "Mörsil",
                            PostNumber = "415 44",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9227)
                        });
                });

            modelBuilder.Entity("WebApplication03.Models.Country", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = "dfa952cd-d673-4da8-8cf7-a980e755e6d5",
                            Name = "Sweden",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9250)
                        },
                        new
                        {
                            Id = "05b559f5-38a9-4651-a285-5034e6466996",
                            Name = "Norway",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9254)
                        },
                        new
                        {
                            Id = "3b5cf351-a249-4091-aa02-075d3250d962",
                            Name = "Danmarc",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9258)
                        });
                });

            modelBuilder.Entity("WebApplication03.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "47d9afec-aabe-41f8-9c3e-9e6f1b64b167",
                            Name = "Svenska",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(8922)
                        },
                        new
                        {
                            Id = "52778a6c-e716-495a-8ab4-411d7e5cfc38",
                            Name = "Persiska",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(8970)
                        },
                        new
                        {
                            Id = "6e733ca0-ac43-45a0-81ca-16dbf2d29955",
                            Name = "Engleska",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(8974)
                        });
                });

            modelBuilder.Entity("WebApplication03.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "6e34a6ea-d8bb-4a0e-8230-b71ebbf53f04",
                            Age = 32,
                            Name = "Ali",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9174)
                        },
                        new
                        {
                            Id = "37f6a1f7-7fa0-4a05-b19e-b2d27a8cb0ac",
                            Age = 32,
                            Name = "Ali 1",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9180)
                        },
                        new
                        {
                            Id = "42c9438f-4e95-4bea-90a6-00f94596abcf",
                            Age = 32,
                            Name = "Ali 2",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 54, 53, 601, DateTimeKind.Local).AddTicks(9184)
                        });
                });

            modelBuilder.Entity("LanguagePerson", b =>
                {
                    b.HasOne("WebApplication03.Models.Language", null)
                        .WithMany()
                        .HasForeignKey("LanguagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication03.Models.Person", null)
                        .WithMany()
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
