// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication03.Data;

#nullable disable

namespace WebApplication03.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221129144423_Seeded data to people table")]
    partial class Seededdatatopeopletable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication03.Models.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Id = "cd84dc9f-f763-4fae-ac42-c349668531e1",
                            Name = "Svenska",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1080)
                        },
                        new
                        {
                            Id = "a13dfdf8-41ef-4e69-9acb-fe038248c2ef",
                            Name = "Persiska",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1116)
                        },
                        new
                        {
                            Id = "63dfe312-d9a4-41f7-bf0f-9dafd4a149ea",
                            Name = "Engleska",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1121)
                        });
                });

            modelBuilder.Entity("WebApplication03.Models.Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Register")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasData(
                        new
                        {
                            Id = "f0011acb-ad28-4a01-9f96-79deed43e9f0",
                            Age = 32,
                            Name = "Ali",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1228)
                        },
                        new
                        {
                            Id = "56097b99-b519-4f28-a58a-941abc2015fe",
                            Age = 32,
                            Name = "Ali 1",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1234)
                        },
                        new
                        {
                            Id = "1a6f95a7-aa50-4c12-aa4c-e3f5dee004e7",
                            Age = 32,
                            Name = "Ali 2",
                            PhoneNumber = "123456",
                            Register = new DateTime(2022, 11, 29, 15, 44, 23, 163, DateTimeKind.Local).AddTicks(1249)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
